# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bookmarksghtest
        ports:
          - 5432/tcp
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Setup Pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: |
        pipenv install

    - name: Install dependencies dev
      run: |
        pipenv install --dev
    - name: Run pyest
      env:
        CONFIG_MODE: 'pytest'
        PYTEST_DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/bookmarksghtest'
      run: |
        pipenv run pytest -s
